# Etapa 1: Build
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./

# Seu projeto usa npm (baseado no package-lock.json)
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Adiciona config do Nginx para lidar com React Router
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]